### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by frol** [ooade/NextSimpleStarter#2] opened 2017-01-26 08:52 UTC
Running the demo app (https://next-preact.now.sh/), I have noticed the following error in the console log:

> Uncaught (in promise) TypeError: Cannot read property 'join' of undefined

**Comment by ooade** [comment] 2017-01-26 12:12
@frol Thanks for checking up on the example app :smile: .

The problem arises from nextjs HeadManager's method "updateTitle" so i don't really have a say about this. I think this issue should be addressed to nextjs itself or preact-compat since it works well with react.

I don't know if @arunoda can take a peek at this.

Steps to reproduce:
- Run the preact example app
- Add nextjs's helper element
- Give the page a title; then that happens.

**Comment by ooade** [comment] 2017-01-28 12:23
It's bin 2days now, i've reported the issue [here](https://github.com/zeit/next.js/issues/910).

**Comment by ooade** [comment] 2017-01-28 22:37
@frol Thanks for the report, it's fixed over there and will be shipped in with the next version of preact-compat, so till then that error will have to wait :smile_cat:

**Comment by ooade** [comment] 2017-01-31 09:55
@frol Now fixed locally. I've exceeded my number of deploys for this month so i'll push it to `now` tomorrow

**Closed by ooade** 2017-01-31 09:55 UTC
